In [2]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
import warnings
warnings.filterwarnings('ignore')

In [3]:
df=pd.read_csv('sonar.csv',names=range(0,61),header=0)
df

0       1       2       3       4       5       6       7       8   \
0    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
1    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
2    0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
3    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
4    0.0286  0.0453  0.0277  0.0174  0.0384  0.0990  0.1201  0.1833  0.2105   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
202  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328   
203  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030   
204  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258   
205  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945   
206  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843   

         9   ...      51      52      53      54      55      56      57  \
0    0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
1    0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
2    0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
3    0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   
4    0.3039  ...  0.0045  0.0014  0.0038  0.0013  0.0089  0.0057  0.0027   
..      ...  ...     ...     ...     ...     ...     ...     ...     ...   
202  0.2684  ...  0.0116  0.0098  0.0199  0.0033  0.0101  0.0065  0.0115   
203  0.2154  ...  0.0061  0.0093  0.0135  0.0063  0.0063  0.0034  0.0032   
204  0.2529  ...  0.0160  0.0029  0.0051  0.0062  0.0089  0.0140  0.0138   
205  0.2354  ...  0.0086  0.0046  0.0126  0.0036  0.0035  0.0034  0.0079   
206  0.2354  ...  0.0146  0.0129  0.0047  0.0039  0.0061  0.0040  0.0036   

         58      59  60  
0    0.0052  0.0044   R  
1    0.0095  0.0078   R  
2    0.0040  0.0117   R  
3    0.0107  0.0094   R  
4    0.0051  0.0062   R  
..      ...     ...  ..  
202  0.0193  0.0157   M  
203  0.0062  0.0067   M  
204  0.0077  0.0031   M  
205  0.0036  0.0048   M  
206  0.0061  0.0115   M  

[207 rows x 61 columns]

In [4]:
df.head()

0       1       2       3       4       5       6       7       8   \
0  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
1  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
2  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
3  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
4  0.0286  0.0453  0.0277  0.0174  0.0384  0.0990  0.1201  0.1833  0.2105   

       9   ...      51      52      53      54      55      56      57  \
0  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
1  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
2  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
3  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   
4  0.3039  ...  0.0045  0.0014  0.0038  0.0013  0.0089  0.0057  0.0027   

       58      59  60  
0  0.0052  0.0044   R  
1  0.0095  0.0078   R  
2  0.0040  0.0117   R  
3  0.0107  0.0094   R  
4  0.0051  0.0062   R  

[5 rows x 61 columns]

In [5]:
df.shape

(207, 61)

In [6]:
x=df.iloc[:,0:60]
x

0       1       2       3       4       5       6       7       8   \
0    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
1    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
2    0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
3    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
4    0.0286  0.0453  0.0277  0.0174  0.0384  0.0990  0.1201  0.1833  0.2105   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
202  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328   
203  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030   
204  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258   
205  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945   
206  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843   

         9   ...      50      51      52      53      54      55      56  \
0    0.2872  ...  0.0125  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140   
1    0.6194  ...  0.0033  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316   
2    0.1264  ...  0.0241  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050   
3    0.4459  ...  0.0156  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072   
4    0.3039  ...  0.0104  0.0045  0.0014  0.0038  0.0013  0.0089  0.0057   
..      ...  ...     ...     ...     ...     ...     ...     ...     ...   
202  0.2684  ...  0.0203  0.0116  0.0098  0.0199  0.0033  0.0101  0.0065   
203  0.2154  ...  0.0051  0.0061  0.0093  0.0135  0.0063  0.0063  0.0034   
204  0.2529  ...  0.0155  0.0160  0.0029  0.0051  0.0062  0.0089  0.0140   
205  0.2354  ...  0.0042  0.0086  0.0046  0.0126  0.0036  0.0035  0.0034   
206  0.2354  ...  0.0181  0.0146  0.0129  0.0047  0.0039  0.0061  0.0040   

         57      58      59  
0    0.0049  0.0052  0.0044  
1    0.0164  0.0095  0.0078  
2    0.0044  0.0040  0.0117  
3    0.0048  0.0107  0.0094  
4    0.0027  0.0051  0.0062  
..      ...     ...     ...  
202  0.0115  0.0193  0.0157  
203  0.0032  0.0062  0.0067  
204  0.0138  0.0077  0.0031  
205  0.0079  0.0036  0.0048  
206  0.0036  0.0061  0.0115  

[207 rows x 60 columns]

In [7]:
y=df.iloc[:,-1]
y

0      R
1      R
2      R
3      R
4      R
      ..
202    M
203    M
204    M
205    M
206    M
Name: 60, Length: 207, dtype: object

In [8]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.2,random_state=42)

In [9]:
lr=LogisticRegression()

In [10]:
lr.fit(x_train,y_train)
lr.score(x_train,y_train)
predlr=lr.predict(x_test)
print('Accuracy_Score= ',accuracy_score(y_test,predlr))
print(confusion_matrix(y_test,predlr))
print(classification_report(y_test,predlr))

Accuracy_Score=  0.7619047619047619
[[18  9]
 [ 1 14]]
              precision    recall  f1-score   support

           M       0.95      0.67      0.78        27
           R       0.61      0.93      0.74        15

    accuracy                           0.76        42
   macro avg       0.78      0.80      0.76        42
weighted avg       0.83      0.76      0.77        42



In [11]:
x_train.shape

(165, 60)

In [12]:
y_train.shape

(165,)

In [13]:
x_test.shape

(42, 60)

In [14]:
y_test.shape

(42,)

# NAIVE BAYES

In [15]:
#Gaussian NB
gnb=GaussianNB()
gnb.fit(x_train,y_train)
gnb.score(x_train,y_train)
predgnb=gnb.predict(x_test)

print('Accuracy Score: ',accuracy_score(y_test,predgnb))
print(confusion_matrix(y_test,predgnb))
print(classification_report(y_test,predgnb))

Accuracy Score:  0.6428571428571429
[[16 11]
 [ 4 11]]
              precision    recall  f1-score   support

           M       0.80      0.59      0.68        27
           R       0.50      0.73      0.59        15

    accuracy                           0.64        42
   macro avg       0.65      0.66      0.64        42
weighted avg       0.69      0.64      0.65        42



In [16]:
from sklearn.naive_bayes import MultinomialNB

In [17]:
mnb=MultinomialNB()
mnb.fit(x_train,y_train)
predmnb=mnb.predict(x_test)
print('Accuracy Score: ',accuracy_score(y_test,predmnb))
print('Confusion Matrix: ', confusion_matrix(y_test,predmnb))

print('Classification Report: ',classification_report(y_test,predmnb))

Accuracy Score:  0.7380952380952381
Confusion Matrix:  [[19  8]
 [ 3 12]]
Classification Report:                precision    recall  f1-score   support

           M       0.86      0.70      0.78        27
           R       0.60      0.80      0.69        15

    accuracy                           0.74        42
   macro avg       0.73      0.75      0.73        42
weighted avg       0.77      0.74      0.74        42



# SUPPORT VECTOR CLASSIFIER

In [18]:
svc=SVC()
svc.fit(x_train,y_train)
svc.score(x_train,y_train)
predsvc=svc.predict(x_test)
print('Accuracy Score= ',accuracy_score(y_test,predsvc))
print(confusion_matrix(y_test,predsvc))
print(classification_report(y_test,predsvc))

Accuracy Score=  0.7619047619047619
[[19  8]
 [ 2 13]]
              precision    recall  f1-score   support

           M       0.90      0.70      0.79        27
           R       0.62      0.87      0.72        15

    accuracy                           0.76        42
   macro avg       0.76      0.79      0.76        42
weighted avg       0.80      0.76      0.77        42



# DECISION TREE CLASSIFIER

In [19]:
dtc=DecisionTreeClassifier()

In [20]:
dtc.fit(x_train,y_train)
dtc.score(x_train,y_train)
preddtc=dtc.predict(x_test)
print('Accuracy Score= ', accuracy_score(y_test,preddtc))
print(confusion_matrix(y_test,preddtc))
print(classification_report(y_test,preddtc))

Accuracy Score=  0.5476190476190477
[[14 13]
 [ 6  9]]
              precision    recall  f1-score   support

           M       0.70      0.52      0.60        27
           R       0.41      0.60      0.49        15

    accuracy                           0.55        42
   macro avg       0.55      0.56      0.54        42
weighted avg       0.60      0.55      0.56        42



# K-NEAREST NEIGHBORS

In [21]:
knn=KNeighborsClassifier()

In [22]:
knn.fit(x_train,y_train)
knn.score(x_train,y_train)
predknn=knn.predict(x_test)
print('Accuracy Score=',accuracy_score(y_test,predknn))
print(confusion_matrix(y_test,predknn))
print(classification_report(y_test,predknn))

Accuracy Score= 0.7380952380952381
[[20  7]
 [ 4 11]]
              precision    recall  f1-score   support

           M       0.83      0.74      0.78        27
           R       0.61      0.73      0.67        15

    accuracy                           0.74        42
   macro avg       0.72      0.74      0.73        42
weighted avg       0.75      0.74      0.74        42



# ENSENBLE TECHNIQUE----- CLASSIFIERS

In [23]:
from sklearn.ensemble import RandomForestClassifier

In [24]:
rf=RandomForestClassifier(n_estimators=100,random_state=42)
#RandomForest Classifier(100 by default)

rf.fit(x_train,y_train)
predrf=rf.predict(x_test)
print(accuracy_score(y_test,predrf))
print(confusion_matrix(y_test,predrf))
print(classification_report(y_test,predrf))

0.7857142857142857
[[22  5]
 [ 4 11]]
              precision    recall  f1-score   support

           M       0.85      0.81      0.83        27
           R       0.69      0.73      0.71        15

    accuracy                           0.79        42
   macro avg       0.77      0.77      0.77        42
weighted avg       0.79      0.79      0.79        42



In [25]:
from sklearn.ensemble import AdaBoostClassifier

In [26]:
#AdaBoostClassifier(base_estimator=DecisionTree Classifier(),n_estimator=50,learning_Rate=1.0)
ad=AdaBoostClassifier()
ad.fit(x_train,y_train)
predad=ad.predict(x_test)
print(accuracy_score(y_test,predad))
print(confusion_matrix(y_test,predad))
print(classification_report(y_test,predad))

0.7142857142857143
[[17 10]
 [ 2 13]]
              precision    recall  f1-score   support

           M       0.89      0.63      0.74        27
           R       0.57      0.87      0.68        15

    accuracy                           0.71        42
   macro avg       0.73      0.75      0.71        42
weighted avg       0.78      0.71      0.72        42



In [27]:
ad=AdaBoostClassifier(n_estimators=50)
ad.fit(x_train,y_train)
predad=ad.predict(x_test)
print(accuracy_score(y_test,predad))
print(confusion_matrix(y_test,predad))
print(classification_report(y_test,predad))

0.7142857142857143
[[17 10]
 [ 2 13]]
              precision    recall  f1-score   support

           M       0.89      0.63      0.74        27
           R       0.57      0.87      0.68        15

    accuracy                           0.71        42
   macro avg       0.73      0.75      0.71        42
weighted avg       0.78      0.71      0.72        42



In [28]:
from sklearn.svm import SVC

In [29]:
svc=SVC()
# Create=adaboost Classifier object
ad=AdaBoostClassifier(n_estimators=50,base_estimator=svc,algorithm='SAMME')
ad.fit(x_train,y_train)
predad=ad.predict(x_test)
print(accuracy_score(y_test,predad))
print(confusion_matrix(y_test,predad))
print(classification_report(y_test,predad))

0.6428571428571429
[[27  0]
 [15  0]]
              precision    recall  f1-score   support

           M       0.64      1.00      0.78        27
           R       0.00      0.00      0.00        15

    accuracy                           0.64        42
   macro avg       0.32      0.50      0.39        42
weighted avg       0.41      0.64      0.50        42



In [30]:
svc=SVC(probability=True,kernel='linear')
ad=AdaBoostClassifier(n_estimators=50,base_estimator=svc)

ad.fit(x_train,y_train)
predad=ad.predict(x_test)
print(accuracy_score(y_test,predad))
print(confusion_matrix(y_test,predad))
print(classification_report(y_test,predad))


0.7142857142857143
[[19  8]
 [ 4 11]]
              precision    recall  f1-score   support

           M       0.83      0.70      0.76        27
           R       0.58      0.73      0.65        15

    accuracy                           0.71        42
   macro avg       0.70      0.72      0.70        42
weighted avg       0.74      0.71      0.72        42



In [31]:
from sklearn.ensemble import GradientBoostingClassifier

In [32]:
gbc=GradientBoostingClassifier()
gbc.fit(x_train,y_train)
gbc.score(x_train,y_train)
predgbc=gbc.predict(x_test)

print(accuracy_score(y_test,predgbc))
print(confusion_matrix(y_test,predgbc))
print(classification_report(y_test,predgbc))

0.8333333333333334
[[23  4]
 [ 3 12]]
              precision    recall  f1-score   support

           M       0.88      0.85      0.87        27
           R       0.75      0.80      0.77        15

    accuracy                           0.83        42
   macro avg       0.82      0.83      0.82        42
weighted avg       0.84      0.83      0.83        42



# CROSS VALIDATION TECHNIQUES

In [34]:
from sklearn.model_selection import cross_val_score
gnbscores=cross_val_score(gnb,x,y,cv=5)
print(gnbscores)
print(gnbscores.mean(),gnbscores.std())

[0.64285714 0.83333333 0.7804878  0.73170732 0.19512195]
0.6367015098722415 0.22951909483457586


In [35]:
from sklearn.model_selection import cross_val_score
svcscores=cross_val_score(svc,x,y,cv=5)
print(svcscores)
print(svcscores.mean(),svcscores.std())

[0.4047619  0.76190476 0.68292683 0.85365854 0.48780488]
0.6382113821138211 0.1678319246920358


In [36]:
dtcscores=cross_val_score(dtc,x,y,cv=5)
print(dtcscores)
print(dtcscores.mean(),dtcscores.std())

[0.54761905 0.64285714 0.6097561  0.73170732 0.68292683]
0.6429732868757261 0.06271497391280735


# PCA-"PRINCIPAL COMPONENT ANALYSIS"

In [37]:
df.shape

(207, 61)

In [38]:
x.shape

(207, 60)

In [42]:
from sklearn.decomposition import PCA

In [43]:
pca=PCA(n_components=10)

In [46]:
x1=pca.fit_transform(x)
x1.shape

(207, 10)

In [47]:
df1=pd.DataFrame(data=x1)
df1

0         1         2         3         4         5         6  \
0   -0.970285  1.017654  0.830432  0.120147  0.299120  0.202682 -0.226988   
1   -0.324435  0.876876  0.228203  0.868926  0.098053 -0.269122 -0.421778   
2    0.853571  0.697734 -0.023602 -0.123425 -0.584388  0.351808  0.478187   
3   -0.061337  0.226034  0.635198  0.152907  0.150982  0.081111 -0.374523   
4   -0.605423  0.901962  0.804550  0.271896  0.496832  0.464410 -0.224909   
..        ...       ...       ...       ...       ...       ...       ...   
202  0.049918 -1.028980  0.265634  0.026018 -0.014738  0.097506  0.012021   
203  0.228374 -1.149870  0.200437  0.043461  0.182020  0.010158  0.084858   
204  0.306763 -1.147756  0.248975 -0.058557  0.161337  0.013778  0.049391   
205 -0.038083 -0.994049  0.201938 -0.060790 -0.147673 -0.088874  0.018656   
206 -0.043904 -0.910802  0.009169 -0.045577 -0.030723 -0.033778  0.025213   

            7         8         9  
0    0.384837  0.004329 -0.082679  
1    0.081072  0.014185 -0.432334  
2   -0.215424 -0.533955 -0.425182  
3    0.070143  0.119454 -0.427480  
4    0.105504 -0.202842 -0.235048  
..        ...       ...       ...  
202  0.178998  0.029362 -0.268631  
203  0.266152 -0.068963 -0.307679  
204  0.227866 -0.070132 -0.313294  
205  0.069504 -0.024406 -0.165303  
206 -0.019100  0.120130 -0.137964  

[207 rows x 10 columns]

In [48]:
# lets do the LabelEncoder

In [50]:
from sklearn.preprocessing import LabelEncoder

In [51]:
le=LabelEncoder()
y1=le.fit_transform(y)
y1

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0])

In [52]:
#STANDARD SCALER

In [53]:
from sklearn.preprocessing import StandardScaler

In [54]:
sc=StandardScaler()

In [55]:
x1=sc.fit_transform(x1)
x1

array([[-1.29978169,  1.70606442,  2.15236817, ...,  1.79447233,
         0.02192769, -0.45429916],
       [-0.43460945,  1.47005543,  0.59147287, ...,  0.37803268,
         0.07184752, -2.37555778],
       [ 1.14343337,  1.16972949, -0.06117199, ..., -1.00450695,
        -2.70454535, -2.33625944],
       ...,
       [ 0.41093512, -1.92417588,  0.64531104, ...,  1.06252591,
        -0.3552279 , -1.72146488],
       [-0.05101567, -1.66649159,  0.5233967 , ...,  0.32409149,
        -0.12362156, -0.90829238],
       [-0.05881343, -1.52693138,  0.02376526, ..., -0.08906321,
         0.60847198, -0.75807236]])

In [56]:
x1.shape

(207, 10)

In [64]:
x1_train,x1_test,y1_train,y1_test=train_test_split(x1,y1,test_size=.2,random_state=45)

In [65]:
x1_train.shape

(165, 10)

In [59]:
y1_train.shape

(165,)

In [60]:
lr=LogisticRegression()

In [66]:
lr.fit(x1_train,y1_train)
lr.score(x1_train,y1_train)
predlr=lr.predict(x1_test)
print(accuracy_score(y1_test,predlr))
print(confusion_matrix(y1_test,predlr))
print(classification_report(y1_test,predlr))

0.8333333333333334
[[20  1]
 [ 6 15]]
              precision    recall  f1-score   support

           0       0.77      0.95      0.85        21
           1       0.94      0.71      0.81        21

    accuracy                           0.83        42
   macro avg       0.85      0.83      0.83        42
weighted avg       0.85      0.83      0.83        42

